/**
 * AgentCore Runtime entrypoint — build-time-export pattern (alternative).
 *
 * Identical to `src/index.ts` except the fully hydrated `BedrockAgentConfig`
 * is **imported from `src/generated/agent.json`**, which
 * `scripts/export-agent.ts` writes at build time (e.g. in CI). The deployed
 * runtime never talks to Airlock at cold start — no `export_agent` call,
 * no `describe_tools` call.
 *
 * Trade-off vs. `index.ts`:
 *   - PRO: no cold-start dependency on Airlock; air-gappable; deterministic.
 *   - CON: every agent-spec change in the Control Room requires a redeploy.
 *
 * Pick one. To use this entrypoint, change the AgentCore Runtime's
 * `CodeConfiguration.EntryPoint` (in `infrastructure/agentcore-stack.ts`) from
 * `index.js` to `build-time-export.js`, and add an `npm run export-agent`
 * step to your build pipeline so `src/generated/agent.json` is present at
 * bundle time.
 *
 * Note: the placeholders the adapter bakes in (`${AIRLOCK_TOKEN}`,
 * `${AIRLOCK_AGENT_INVOCATION_ID}`) are still placeholders in the generated
 * JSON — they're substituted at invocation time, never written to disk
 * resolved. The deployed artifact carries no secrets.
 */

import { BedrockAgentCoreApp } from 'bedrock-agentcore/runtime';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';

import { renderConfig } from './lib/render-config.ts';
import { runAgent } from './lib/run-agent.ts';
import { getServiceToken } from './lib/service-token.ts';
import type { BedrockAgentConfig } from './lib/types.ts';

// Generated by `scripts/export-agent.ts`. Build will fail if it's missing —
// that's intentional: the build-time pattern requires it.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated module; present after `npm run export-agent`.
import generatedConfig from './generated/agent.json' with { type: 'json' };

const config = generatedConfig as BedrockAgentConfig;

const requestSchema = z.object({
  prompt: z.string().min(1, 'prompt is required'),
});

const app = new BedrockAgentCoreApp({
  invocationHandler: {
    requestSchema,
    process: async function* (request) {
      const serviceToken = await getServiceToken();
      const agentInvocationId = randomUUID();
      const rendered = renderConfig(config, { serviceToken, agentInvocationId });

      yield {
        event: 'invocation_started',
        data: { agentInvocationId, model: rendered.converse.modelId },
      };

      yield* runAgent(request.prompt, rendered);
    },
  },
});

app.run();
